# Generated by Django 4.1.7 on 2023-04-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrayimage',
            name='xray_img',
            field=models.ImageField(upload_to='./images/'),
        ),
    ]
