# Generated by Django 4.1.2 on 2023-07-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0003_xrayimage_prediction_xrayimage_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayimage',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='proposed_evaluation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
