# Generated by Django 4.1.2 on 2023-07-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0004_xrayimage_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayimage',
            name='user_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
