# Generated by Django 4.1.2 on 2023-07-22 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0005_xrayimage_user_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xrayimage',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='xrayimage',
            name='proposed_evaluation',
        ),
    ]
