# Generated by Django 4.1.2 on 2025-08-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0006_remove_xrayimage_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayimage',
            name='xray_img_det',
            field=models.ImageField(blank=True, null=True, upload_to='./images/detection/'),
        ),
        migrations.AddField(
            model_name='xrayimage',
            name='xray_img_origin',
            field=models.ImageField(blank=True, null=True, upload_to='./images/original/'),
        ),
    ]
