# Generated by Django 4.1.2 on 2023-03-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(default='127.0.0.1:8000/', verbose_name='127.0.0.1:8000/image'),
            preserve_default=False,
        ),
    ]
